# Generated by Django 4.2 on 2023-09-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wefund_login', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
    ]
