# Generated by Django 4.2 on 2023-09-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund_login', '0004_auto_20230910_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monthly_revenue',
            field=models.PositiveIntegerField(choices=[(0, '0 - 42,000'), (1, '42,001 - 83,000'), (2, '83,001 - 167,000'), (3, '167,001 - 417,000'), (4, '417,001 - 833,000'), (5, '833,001 - 1,700,000')], default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='years_in_business',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
