# Generated by Django 4.2 on 2023-12-19 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wefund_login', '0005_customuser_monthly_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forget_password_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
